// Datos simulados de programas
export const PROGRAMAS = [
  { id: "1", nombre: "Ingeniería de Sistemas" },
  { id: "2", nombre: "Administración de Empresas" },
  { id: "3", nombre: "Psicología" },
  { id: "4", nombre: "Derecho" },
]

// Datos simulados de profesores
export const PROFESORES = [
  {
    id: "1",
    nombre: "Juan Pérez",
    programa: "1",
    materias: ["Programación I", "Bases de Datos"],
    evaluaciones: [
      { aspecto: "dominio", promedio: 0.9 },
      { aspecto: "cumplimiento", promedio: 0.85 },
      { aspecto: "calidad", promedio: 0.88 },
      { aspecto: "puntualidad", promedio: 0.95 },
      { aspecto: "metodologia", promedio: 0.82 },
      { aspecto: "recursos", promedio: 0.78 },
      { aspecto: "evaluacion", promedio: 0.86 },
      { aspecto: "motivacion", promedio: 0.92 },
      { aspecto: "relaciones", promedio: 0.94 },
    ],
    promedioGeneral: 0.88,
    totalEvaluaciones: 15,
  },
  {
    id: "2",
    nombre: "María López",
    programa: "1",
    materias: ["Algoritmos", "Estructuras de Datos"],
    evaluaciones: [
      { aspecto: "dominio", promedio: 0.95 },
      { aspecto: "cumplimiento", promedio: 0.92 },
      { aspecto: "calidad", promedio: 0.9 },
      { aspecto: "puntualidad", promedio: 0.88 },
      { aspecto: "metodologia", promedio: 0.93 },
      { aspecto: "recursos", promedio: 0.85 },
      { aspecto: "evaluacion", promedio: 0.89 },
      { aspecto: "motivacion", promedio: 0.91 },
      { aspecto: "relaciones", promedio: 0.94 },
    ],
    promedioGeneral: 0.91,
    totalEvaluaciones: 12,
  },
  {
    id: "3",
    nombre: "Carlos Rodríguez",
    programa: "2",
    materias: ["Administración Financiera", "Contabilidad"],
    evaluaciones: [
      { aspecto: "dominio", promedio: 0.82 },
      { aspecto: "cumplimiento", promedio: 0.79 },
      { aspecto: "calidad", promedio: 0.75 },
      { aspecto: "puntualidad", promedio: 0.8 },
      { aspecto: "metodologia", promedio: 0.72 },
      { aspecto: "recursos", promedio: 0.68 },
      { aspecto: "evaluacion", promedio: 0.71 },
      { aspecto: "motivacion", promedio: 0.65 },
      { aspecto: "relaciones", promedio: 0.7 },
    ],
    promedioGeneral: 0.74,
    totalEvaluaciones: 18,
  },
  {
    id: "4",
    nombre: "Ana Martínez",
    programa: "2",
    materias: ["Marketing", "Gestión de Proyectos"],
    evaluaciones: [
      { aspecto: "dominio", promedio: 0.78 },
      { aspecto: "cumplimiento", promedio: 0.82 },
      { aspecto: "calidad", promedio: 0.8 },
      { aspecto: "puntualidad", promedio: 0.85 },
      { aspecto: "metodologia", promedio: 0.79 },
      { aspecto: "recursos", promedio: 0.75 },
      { aspecto: "evaluacion", promedio: 0.77 },
      { aspecto: "motivacion", promedio: 0.81 },
      { aspecto: "relaciones", promedio: 0.83 },
    ],
    promedioGeneral: 0.8,
    totalEvaluaciones: 14,
  },
  {
    id: "5",
    nombre: "Roberto Gómez",
    programa: "3",
    materias: ["Psicología Clínica", "Neuropsicología"],
    evaluaciones: [
      { aspecto: "dominio", promedio: 0.88 },
      { aspecto: "cumplimiento", promedio: 0.85 },
      { aspecto: "calidad", promedio: 0.87 },
      { aspecto: "puntualidad", promedio: 0.82 },
      { aspecto: "metodologia", promedio: 0.84 },
      { aspecto: "recursos", promedio: 0.8 },
      { aspecto: "evaluacion", promedio: 0.83 },
      { aspecto: "motivacion", promedio: 0.86 },
      { aspecto: "relaciones", promedio: 0.89 },
    ],
    promedioGeneral: 0.85,
    totalEvaluaciones: 20,
  },
]

// Mapeo de aspectos a nombres legibles
export const ASPECTOS_NOMBRES = {
  dominio: "Dominio del tema",
  cumplimiento: "Cumplimiento",
  calidad: "Calidad",
  puntualidad: "Puntualidad",
  metodologia: "Metodología",
  recursos: "Recursos",
  evaluacion: "Evaluación",
  motivacion: "Motivación",
  relaciones: "Relaciones",
}

